/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

grammar test1;

init : HTMLTAG head;
HTML_COMMENT : HEADCOMMENT_SECTION+ ->skip;
HEADCOMMENT_SECTION:'<!' .*? '>'|'<!--'.*?'-->' ;
head: HEAD_TAG HEAD_DATA* HEAD_TAG;
//body :BODY_TAG body_data* BODY_TAG ;
//body_data:div_class;
//div_class:div_class|link_class|DIV_CLASS_DEFN;
//link_class:LINK|SPAN LINK SPAN;
//LINK:LINK_STRUCT LETTERS LINK_STRUCT;
//LINK_STRUCT:STARTENDINDENT 'a href' .*? STARTENDINDENT|STARTENDINDENT ENDTAG 'a' STARTENDINDENT;
//SPAN:LETTERS;
//DIV_CLASSS_DEFN:STARTENDINDENT 'div class' .*? STARTENDINDENT|STARTENDINDENT ENDTAG 'div' STARTENDINDENT;

//BODY_TAG: STARTENDINDENT 'body' STARTENDINDENT|STARTENDINDENT ENDTAG 'body' STARTENDINDENT|STARTENDINDENT 'body' .*? STARTENDINDENT;
HEAD_DATA:METATAG|LINKTAG|TITLETAG|SCRIPTTAG;
METATAG:STARTENDINDENT 'meta'.*? STARTENDINDENT;
LINKTAG : STARTENDINDENT 'link' .*? STARTENDINDENT;
TITLETAG : STARTENDINDENT 'title'STARTENDINDENT .*? STARTENDINDENT ENDTAG 'title' STARTENDINDENT;
SCRIPTTAG: STARTENDINDENT 'script' .*? STARTENDINDENT|STARTENDINDENT ENDTAG 'script' STARTENDINDENT;
HTMLTAG : STARTENDINDENT 'html' STARTENDINDENT|STARTENDINDENT 'HTML' STARTENDINDENT|STARTENDINDENT ENDTAG'html' STARTENDINDENT |STARTENDINDENT ENDTAG'HTML' STARTENDINDENT |HTMLASSIGNTAG;
HTMLASSIGNTAG :STARTENDINDENT 'html' .*? '='.*? STARTENDINDENT;
HEAD_TAG :STARTENDINDENT 'head' STARTENDINDENT|STARTENDINDENT ENDTAG 'head' STARTENDINDENT;
STARTENDINDENT : '<'|'>';
SPLEXP :'!'|'=';
ENDTAG : '/';
LETTERS :[a-zA-Z]+;
WS : [ \t\r\n]+ -> skip;