/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

grammar test1_ammended;

init : HTMLTAG head;
HTML_COMMENT : HEADCOMMENT_SECTION+ ->skip;
HEADCOMMENT_SECTION:'<!--<' .*? '>-->'|'<!' .*? '>'|'<!--'.*?'-->'|'<!' .*? '-->' ;
head: HEAD_TAG head_data HEAD_TAG;
//body :BODY_TAG body_data* BODY_TAG ;
//body_data:div_class;
//div_class:div_class|link_class|DIV_CLASS_DEFN;
//link_class:LINK|SPAN LINK SPAN;
//LINK:LINK_STRUCT LETTERS LINK_STRUCT;
//LINK_STRUCT:STARTENDINDENT 'a href' .*? STARTENDINDENT|STARTENDINDENT ENDTAG 'a' STARTENDINDENT;
//SPAN:LETTERS;
//DIV_CLASSS_DEFN:STARTENDINDENT 'div class' .*? STARTENDINDENT|STARTENDINDENT ENDTAG 'div' STARTENDINDENT;

//BODY_TAG: STARTENDINDENT 'body' STARTENDINDENT|STARTENDINDENT ENDTAG 'body' STARTENDINDENT|STARTENDINDENT 'body' .*? STARTENDINDENT;
head_data:(METATAG|LINKTAG|TITLETAG|SCRIPTTAG)+;
METATAG:STARTINDENT 'meta'.*? ENDINDENT;
LINKTAG : STARTINDENT 'link' .*? ENDINDENT|STARTINDENT 'link' .*? ENDTAG ENDINDENT;
TITLETAG : STARTINDENT 'title'ENDINDENT .*? STARTINDENT ENDTAG 'title' ENDINDENT;
SCRIPTTAG: STARTINDENT 'script' .*? ENDINDENT|STARTINDENT ENDTAG 'script' ENDINDENT;
HTMLTAG : STARTINDENT 'html' ENDINDENT|STARTINDENT 'HTML' ENDINDENT|STARTINDENT ENDTAG'html' ENDINDENT |STARTINDENT ENDTAG'HTML' ENDINDENT |HTMLASSIGNTAG;
HTMLASSIGNTAG :STARTINDENT 'html' .*? '='.*? ENDINDENT;
HEAD_TAG :STARTINDENT 'head' ENDINDENT|STARTINDENT ENDTAG 'head' ENDINDENT;
STARTINDENT : '<';
ENDINDENT : '>';
SPLEXP :'!'|'=';
ENDTAG : '/';
LETTERS :[a-zA-Z]+;
WS : [ \n\t\r]+ -> skip;
